name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build IPA
        run: |
          xcodebuild -project Websmith.xcodeproj -scheme WebsmithApp -sdk iphoneos -configuration Release -archivePath build/Websmith.xcarchive archive
          xcodebuild -exportArchive -archivePath build/Websmith.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebsmithApp.ipa
          path: build/*.ipa
