name: iOS starter workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive unsigned
        env: { SCHEME: Websmith }
        run: |
          xcodebuild \
            -project Websmith.xcodeproj \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/Websmith.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive
      - name: Create unsigned .ipa
        run: |
          mkdir -p Payload
          cp -R "build/Websmith.xcarchive/Products/Applications/"*.app Payload/
          (cd Payload && /usr/bin/zip -r ../Websmith-unsigned.ipa .)
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app.ipa
          path: build/*.ipa
          if-no-files-found: error
          retention-days: 7
          overwrite: true
